### ISSUE TITLE
Code 128 Error with "+" Symbol

### ISSUE THREAD

**Issue by Akantor47** [kreativekorp/barcode#10]
Hello, 

I got some errors with my code 128 barcode.
I am using it for openssl strings, and if in this string a "+" Symbol occures it just doesn't occure in the barcode picture.

As far as I know the barcode 128 should allow the + Symbol.
I would need some help. Thank you.

FYI:
I am Using not the class as a class. I am using the httpurl to create the image.

**Comment by RebeccaRGB** [comment]
Use %2B instead of + to encode the + symbol. The + symbol has a special meaning in URLs so it has to be escaped.
