### ISSUE TITLE
some characters are not generated

### ISSUE THREAD

**Issue by BrooklynElectronicsGroup** [kreativekorp/barcode#5]
characters such as   #     +    are not passed through/generated on code128, qr, datamatrix ...etc....  is this by design?

**Comment by RebeccaRGB** [comment]
You will need to URL-escape those characters since they have special meaning in URLs. # will need to be passed through as %23, + as %2B, etc. See this chart for reference: http://www.kreativekorp.com/charset/unicode.php?block=0000
